log_level: "info"  # Log level: panic, fatal, error, warn, info, debug, trace

# LND connection settings
lnd:
  host: "localhost"
  port: 10009
  tls_cert_path: "~/.lnd/tls.cert"
  macaroon_path: "~/.lnd/data/chain/bitcoin/mainnet/readonly.macaroon"

# Notification formatting settings
formatting:
  locale: "en-US"  # Language for number formatting (e.g. "en-US" for English, "de-DE" for German)

# Notification settings
notifications:
  providers:
    - url: "discord://token@channel?SplitLines=false"  # Discord webhook URL
      name: "main-discord"
  templates:
    channel_close_event: "🔒 Channel closed with {{.PeerAlias}}, settled balance {{.SettledBalance}} sats"
    channel_open_event: "🚀 Channel opened with {{.PeerAlias}}, capacity {{.Capacity}} sats"
    failed_htlc_event: "❌ Failed HTLC of {{.Amount}} sats\\n{{.InChanAlias}} -> {{.OutChanAlias}}\\nReason: {{.WireFailure}} ({{.FailureDetail}})\\nActual Outbound: {{.OutChanLiquidity}} sats\\nMissed Fee: {{.MissedFee}} sats"
    forward_event: "💰 Forwarded {{.Amount}} sats, {{.PeerAliasIn}} -> {{.PeerAliasOut}}, earned {{.Fee}} sats"
    invoice_settled_event: "💵 Invoice settled: {{or .Memo \"No Memo\"}} for {{.Value}} sats"
    keysend_event: "📨 Keysend received:\n\n{{.Msg}}\n\nChannel In: {{.InChanAlias}} ({{.InChanId}})"
    payment_succeeded_event: "⚡️ Payment: {{.Amount}} sats (fee: {{.Fee}}, {{.FeeRate}} ppm) to {{.Receiver}}{{if .Memo}} - {{.Memo}}{{end}}{{range .HtlcInfo}}\n  Route: {{range $i, $hop := .HopInfo}}{{if $i}} -> {{end}}{{$hop.Alias}} ({{$hop.FeeRate}} ppm){{end}}{{end}}\nHash: {{.PaymentHash}}"
    peer_offline_event: "{{if .PeerAlias}}⚠️ Peer {{.PeerAlias}} ({{.PeerPubkeyShort}}) went offline{{else}}⚠️ Peer {{.PeerPubKey}} went offline{{end}}"
    peer_online_event: "{{if .PeerAlias}}✅ Peer {{.PeerAlias}} ({{.PeerPubkeyShort}}) is online{{else}}✅ Peer {{.PeerPubKey}} is online{{end}}"
    rebalancing_succeeded_event: "{{range .HtlcInfo}}☯️ Rebalanced {{.Amount}} sats {{.FirstHop}} → {{.PenultHop}}. Fee: {{.Fee}} sats ({{.FeeRate}} ppm), Route: {{range $i, $hop := .HopInfo}}{{if $i}} -> {{end}}{{$hop.Alias}} ({{$hop.FeeRate}} ppm){{end}}\n{{end}}"
    on_chain_mempool_event: "🔗 Discovered On-Chain transaction in mempool: {{.Amount}} sats\nFee: {{.TotalFees}} sats\n\nOutputs:\n{{range .Outputs}}- {{.Amount}} sats to {{.Address}} ({{.OutputType}}{{if .IsOurAddress}}, ours{{end}})\n{{end}}\nTxID: {{.TxHash}}\nRaw TX: {{.RawTxHex}}"
    on_chain_confirmed_event: "🔗 Confirmed On-Chain transaction: {{.Amount}} sats\nFee: {{.TotalFees}} sats\n\nTxID: {{.TxHash}}"

# Event settings (feature flags)
events:
  channel_events: true # Enable channel events (open/close) notifications
  failed_htlc_events: true # Enable failed HTLC notifications
  forward_events: true # Enable payment forwarding notifications
  invoice_events: true # Enable invoice settled notifications
  keysend_events: true # Enable keysend notifications
  payment_events: true # Enable outgoing payment succeeded notifications
  peer_events: true # Enable peer events (online/offline) notifications
  rebalancing_events: true # Enable rebalancing succeeded notifications
  status_events: true # Enable status change notifications (startup/shutdown)
  on_chain_events: true # Enable on-chain transaction notifications

# Event configuration (specific settings for each event type)
event_config:
  failed_htlc_event:
    min_amount: 0  # Minimum amount in sats to notify about failed HTLC event
  forward_event:
    min_amount: 0  # Minimum outgoing amount in sats to notify about forward event
  invoice_event:
    min_amount: 0  # Minimum amount in sats to notify about invoice event
  payment_event:
    min_amount: 0  # Minimum amount in sats to notify about payment succeeded event
  rebalancing_event:
    min_amount: 0  # Minimum amount in sats to notify about rebalancing
  on_chain_event:
    min_amount: 0  # Minimum amount in sats to notify about on-chain transaction
