log_level: "info"  # Log level: panic, fatal, error, warn, info, debug, trace

# LND connection settings
lnd:
  host: "localhost"
  port: 10009
  tls_cert_path: "~/.lnd/tls.cert"
  macaroon_path: "~/.lnd/data/chain/bitcoin/mainnet/readonly.macaroon"

# Notification settings
notifications:
  providers:
    - url: "discord://token@channel?SplitLines=false"  # Discord webhook URL
      name: "main-discord"
  templates:
    forward_event: "💰 Forwarded {{.Amount}} sats, {{.PeerAliasIn}} -> {{.PeerAliasOut}}, earned {{.Fee}} sats"
    peer_online_event: "{{if .PeerAlias}}✅ Peer {{.PeerAlias}} ({{.PeerPubkeyShort}}) is online{{else}}✅ Peer {{.PeerPubKey}} is online{{end}}
    peer_offline_event: "{{if .PeerAlias}}⚠️ Peer {{.PeerAlias}} ({{.PeerPubkeyShort}}) went offline{{else}}⚠️ Peer {{.PeerPubKey}} went offline{{end}}"
    channel_open_event: "🚀 Channel opened with {{.PeerAlias}}, capacity {{.Capacity}} sats"
    channel_close_event: "🔒 Channel closed with {{.PeerAlias}}, settled balance {{.SettledBalance}} sats"
    invoice_settled_event: "💵 Invoice settled: {{or .Memo \"No Memo\"}} for {{.Value}} sats"
    failed_htlc_event: "❌ Failed HTLC of {{.Amount}} sats\\n{{.InChanAlias}} -> {{.OutChanAlias}}\\nReason: {{.WireFailure}} ({{.FailureDetail}})\\nActual Outbound: {{.OutChanLiquidity}} sats\\nMissed Fee: {{.MissedFee}} sats"
    keysend_event: "📨 Keysend received:\n\n{{.Msg}}\n\nChannel In: {{.InChanAlias}} ({{.InChanId}})"

# Event settings (feature flags)
events:
  forward_events: true  # Enable payment forwarding notifications
  peer_events: true # Enable peer events (online/offline) notifications
  channel_events: true # Enable channel events (open/close) notifications
  invoice_events: true # Enable invoice settled notifications
  failed_htlc_events: true # Enable failed HTLC notifications
  status_events: true # Enable status change notifications (startup/shutdown)
  keysend_events: true # Enable keysend notifications

# Event configuration (specific settings for each event type)
event_config:
  forward_event:
    min_amount: 0  # Minimum outgoing amount in sats to notify about forward event
  invoice_event:
    min_amount: 0  # Minimum amount in sats to notify about invoice event
  failed_htlc_event:
    min_amount: 0  # Minimum amount in sats to notify about failed HTLC event
